### ISSUE TITLE
[Bug]:  PDV missing on Nodes when running in parallel

### ISSUE THREAD

**Issue by kkmaute** [kkmaute/moris#7]
### Problem Type

Error

### Input File and Problem Description

Failure when run on 16 processors with 

***          Pdv_Host_Manager::communicate_check_if_owned_pdv_exists - PDV missing on Node with ID 46276 on Proc 9.

[log.txt](https://github.com/kkmaute/moris/files/12433859/log.txt)
[uBend_2D_Optimization.txt](https://github.com/kkmaute/moris/files/12433876/uBend_2D_Optimization.txt)

### Command Line

moris.sh dbg 16 uBend_2D_Optimization

### Minimal Example

- [X] I have included a minimal example for recreating this bug

### Memory Violation and Leak Check

- [X] I have checked for memory violations and leaks

### Operating System

Linux

### Code Version

- [X] dbg (MORIS_HAVE_DEBUG = TRUE)
- [X] opt (MORIS_HAVE_DEBUG = FALSE)

### Processors

- [ ] Serial
- [X] Parallel

### Dependence

Mesh refinement dependence?
---------------------------

Fails on any mesh refinement (tNumElements = 2, 5)

Partition dependence?
---------------------

Fails only on runs with 16, 24, 32 procs

**Comment by apchristopherson** [comment]
This bug has been fixed in #8 . 

As a brief summary, the issue was that if a processor boundary aligned exactly with a mesh set boundary, and a PDV is defined on one mesh set but not the other, the mesh does not return the nodes on the processor boundary as being part of the requested mesh set. Thus, no PDVs are created on these nodes. This becomes a problem if the nodes in question are owned by the processor that does not know about the mesh set, because then PDV IDs are not created for the specified PDV type on these nodes. 

Now, node IDs that are found on a mesh set with a PDV type are communicated to the owning processor in order to register these nodes for PDV host creation. From this information, a node index and node coordinates are found locally through the background mesh. The PDV hosts may already exist on the owning processor at the time that the shared node IDs are received, but this is already handled in the PDV host manager. The PDVs themselves are also created just after the hosts to take advantage of these communicated IDs, with duplicate PDV values being handled in a similar fashion.
